file = open ("Retrieval_Queries.sql", "r")
file1 = open ("quries.sql","w")
file = file.read()
file = file.replace("\n"," ")
file = file.replace("   "," ")
file = file.replace("              "," ")
sql = file.split(";")
for qurrie in sql:
    file1.write(qurrie+"\n")
print(sql)